version: '3'
services:
  mysql:
    image: mysql:5.6
    restart: always
    container_name: nest_mysql
    ports:
      - "3336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
    volumes:
      - ./mysql-data:/var/lib/mysql